new test

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -1,5 +1,5 @@
 name: Test
-concurrency: test-${{ github.ref }}
+concurrency: production
 
 on:
   push:
@@ -19,39 +19,34 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: '20'
-          cache: 'npm'
+          cache: 'npm' # Cache npm dependencies
 
       - name: Install dependencies
         run: npm ci
 
+      - name: Run tests
+        run: npm run test:unit
+
+      - name: Display test results
+        if: failure() # This step runs only if the tests fail
+        run: cat ./test-results.txt || echo "No test results file found"
+      
+      - name: Start the server
+        run: npm start &
+        env:
+          NODE_ENV: test
+      - name: Wait for the server to be ready
+        run: npx wait-on http://localhost:3030
+
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
 
-      - name: Run Jest tests
-        run: npm run test:unit
-        env:
-          CI: true
-
       - name: Run Playwright tests
         run: npm run test:e2e
-        env:
-          CI: true
 
-      - name: Collect Jest results
-        if: always()
-        run: cat ./reports/jest/jest-results.xml || echo "No Jest results found"
-        id: jest_summary
-
-      - name: Collect Playwright results
-        if: always()
-        run: cat ./reports/playwright/playwright-results.xml || echo "No Playwright results found"
-        id: playwright_summary
-
-      - name: Generate Summary
-        if: always()
-        run: |
-          echo "## Test Summary" >> $GITHUB_STEP_SUMMARY
-          echo "### Jest Results" >> $GITHUB_STEP_SUMMARY
-          cat ./reports/jest/jest-results.xml >> $GITHUB_STEP_SUMMARY || echo "No Jest results available"
-          echo "### Playwright Results" >> $GITHUB_STEP_SUMMARY
-          cat ./reports/playwright/playwright-results.xml >> $GITHUB_STEP_SUMMARY || echo "No Playwright results available"
+      - uses: actions/upload-artifact@v4
+        if: ${{ !cancelled() }}
+        with:
+          name: playwright-report
+          path: playwright-report/
+          retention-days: 30
